### ISSUE TITLE
No network connection message not shown on Stats Insights page

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-iOS#12076]
### Expected behavior

A page looking like this, 

![IMG_2840](https://user-images.githubusercontent.com/6520461/60828951-66d72000-a179-11e9-91bb-78c6a05e4c8c.PNG)

or cached data

### Actual behavior
![IMG_2838](https://user-images.githubusercontent.com/6520461/60828970-70608800-a179-11e9-9aa2-e0d0507db6c1.PNG)

![IMG_2839](https://user-images.githubusercontent.com/6520461/60828978-75253c00-a179-11e9-9013-67a7a2641caf.PNG)

### Steps to reproduce the behavior

Go to Stats > Insights, activate airplane mode and disable WiFi then pull to refresh

##### Tested on [device], iOS [version], WPiOS [version]
 iPhone X, 12.2, WPv12.8.0.2

**Comment by ScoutHarris** [comment]
@danielebogo - can you look at this please?

**Comment by danielebogo** [comment]
@ScoutHarris @JavonDavis This should be fixed [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/12055) Basically we didn't notify the view to display the loader when the Stats Period Overview refresh was triggered while one was in progress.

**Comment by JavonDavis** [comment]
@danielebogo I'm still seeing this on WP12.9... For example when I go Stats > Insights > Today > View More > Turn on Airplane mode > Pull to refresh

**Comment by danielebogo** [comment]
Hey @JavonDavis is this only happening in a _detail view_ (ex. opening a view clicking on View More)? Do you still have the problem in Insights overview? Because [this](https://github.com/wordpress-mobile/WordPress-iOS/pull/12055) fixed the problem for the overview.

**Comment by JavonDavis** [comment]
Ahh sorry I just grouped them in my mind! no I'm not having it for the overview anymore 👍 Should I go ahead and open an issue for the _detail view_?

**Comment by danielebogo** [comment]
@JavonDavis no problem! Yes another Issue would be great! Feel free to assign it to me 😉

**Comment by JavonDavis** [comment]
Fixed with #12055
