### ISSUE TITLE
Crash in Reader after putting the app in the background while viewing an individual post

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12554]
Steps to reproduce:

1. Open an individual post in the Reader.
1. Minimize the app.

**Result:** the app crashes with a notice that says "WordPress Crashed Do you want to share additional information with the developer?" ([25s](https://cloudup.com/cTleV09vuvp))

<img src="https://user-images.githubusercontent.com/1119271/65641533-44031d80-dfaa-11e9-90bb-928fb3314b58.png" width="270" alt="wordpress-crashed">
<sup>Tested with WPiOS 13.0.0.0 (TestFlight) on iPhone 6S iOS 13.1 beta 4.</sup>

**Comment by koke** [comment]
Seeing this in the crash:

>Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-create watchdog transgression: org.wordpress exhausted CPU time allowance of 4.41 seconds | ProcessVisibility: Background | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 20.310 (user 20.310, system 0.000), 43% CPU", | "Elapsed application CPU time (seconds): 5.221, 11% CPU" | )

**Comment by koke** [comment]
This is becoming an interesting puzzle, but first I want to clarify that this doesn't seem like a regular crash.

The new "crash reporter" in TestFlight gets triggered (and a crash report is generated on the device) but the app doesn't actually exit. While running from Xcode, instead of the crash I can see this in the console, but the process continues running:

> 2019-09-26 09:52:12.849515+0200 WordPress[2590:453240] Can't end BackgroundTask: no background task exists with identifier 81 (0x51), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

If I look at the app logs, I can see that the app goes to the background and comes back without a relaunch:

```
2019-09-26 09:51:15:208 🔵 Tracked: reader_accessed
2019-09-26 09:51:15:278 🔵 Tracked: reader_article_opened <blog_id: 5089392, feed_id: 34277, feed_item_id: 2427065343, is_jetpack: 0, offline_view: no, post_detail_type: normal, post_id: 96107>
2019-09-26 09:51:15:977 <WordPress.WordPressAppDelegate: 0x2821b3000> applicationWillResignActive(_:)
2019-09-26 09:51:16:014 Stats: finished persisting Period Stats to disk.
2019-09-26 09:51:16:935 <WordPress.WordPressAppDelegate: 0x2821b3000> applicationDidEnterBackground(_:)
2019-09-26 09:51:16:957 🔵 Tracked: application_closed <last_visible_screen: Reader, time_in_app: 188>
2019-09-26 09:51:16:972 PingHub disconnecting
2019-09-26 09:51:17:189 PingHub disconnected: WSError(type: Starscream.ErrorType.protocolError, message: "", code: 1000)
2019-09-26 09:51:17:189 TracksService sendQueuedEvents completed. Sent 2 events.
2019-09-26 09:51:22:420 <WordPress.WordPressAppDelegate: 0x2821b3000> applicationWillEnterForeground(_:)
2019-09-26 09:51:22:420 PingHub connecting
2019-09-26 09:51:22:662 <WordPress.WordPressAppDelegate: 0x2821b3000> applicationDidBecomeActive(_:)
2019-09-26 09:51:22:663 🔵 Tracked: application_opened
```

My working theory is that the process that tries to take a snapshot of the app for the app switcher is what's failing here. I could see this in the device logs from the Console app:

```
com.apple.WebKit	Network	0x12988cdb0 - FrameLoader::prepareForLoadStart: Starting frame load (frame = 0x109904f80, main = 1)
com.apple.WebKit	Network	0x10990a3a0 - ProgressTracker::progressStarted: frame 0x109904f80, value 0.100000, tracked frames 1, originating frame 0x109904f80, isMainLoad 1
com.apple.WebKit	Network	0x10a2bc000 - DocumentLoader::startLoadingMainResource: Starting load (frame = 0x109904f80, main = 1)
com.apple.WebKit	Network	0x10a2bc000 - DocumentLoader::startLoadingMainResource: Returning substitute data (frame = 0x109904f80, main = 1)
com.apple.WebKit	Network	0x10a2bc000 - DocumentLoader::startLoadingMainResource callback: Load canceled because of substitute data (frame = 0x109904f80, main = 1)
*** Assertion failure in void _prepareForCAFlush(UIApplication *__strong)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.22.15/UIApplication.m:2914
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unexpected start state'
*** First throw call stack:
(0x198ef9c30 0x198c140c8 0x198df675c 0x1992896c0 0x19cf88664 0x19cfb98f0 0x198e7467c 0x198e6f31c 0x198e6f0b8 0x19c491a9c 0x19c494484 0x19c4e5dc4 0x19c4943dc 0x104ece890 0x104df0d20 0x104fda27c 0x104e369cc 0x104de1d04 0x104ddc960 0x104ddc9ac 0x19c957040 0x19c9572e4 0x19d437688 0x198c0faf0 0x19f9d60f4 0x19f9d63fc 0x19d42341c 0x19c8c7a94 0x19c8c1f70 0x19c8c8e28 0x19c8ca0f8 0x19c8ad4e0 0x19d437abc 0x198c0faf0 0x19f9d60f4 0x19f9d63fc 0x19f9e9964 0x19f92ec1c 0x19f959bd8 0x19cf98efc 0x19cf98204 0x19cf98e30 0x19d429f60 0x19cf98bb0 0x19c5a4bc0 0x19d1c80e8 0x19cf98a6c 0x19cf9a510 0x19e0ade6c 0x19e0adec0 0x19e0ada3c 0x19cf9a434 0x19cf99918 0x19cf9a2d4 0x19c5a4aac 0x19c5a4d18 0x19cf9a014 0x19d4c76b4 0x19d4c78c4 0x19cf9ab78 0x19d4c7530 0x19c5a42a8 0x19c5a5360 0x19cb3123c 0x19e063b1c 0x19e08a128 0x19e06e0f8 0x19e08a044 0x198ba100c 0x198ba3d50 0x19e0b0384 0x19e0b0030 0x19e0b<…>
```

**Comment by koke** [comment]
For completeness, these are all the warnings/errors that appeared in the Xcode console before putting the app in the background. Not sure how many (if any) are related to this, but they seem worth investigating:

```
[error] fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
[error] CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: warning: Property 'customProperties' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
CoreData: warning: Property 'deviceInfo' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
CoreData: warning: Property 'userProperties' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
[TraitCollection] Class WordPress.WPSplitViewController overrides the -traitCollection getter, which is not supported. If you're trying to override traits, you must use the appropriate API.
[TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x10b06c200; frame = (0 22; 375 812); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x2801ae160>; layer = <CALayer: 0x280fe1d60>; contentOffset: {0, 0}; contentSize: {375, 59006}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <WPTableViewHandler: 0x283c42010>>
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 9223372036854775806
!!! Suppressing further NSLayoutTree logs
```

**Comment by koke** [comment]
I found [this thread](https://forums.developer.apple.com/message/380496) in the developer forums where other developers are seeing the same messages about background tasks, I think this might be an iOS bug.

> Same here with empty new project in iOS 13 GM with Xcode 11 GM on iPhone XS Max & on iOS 13.1 Beta 3 on iPhone XS.
>
> Can't end BackgroundTask: no background task exists with identifier 2 (0x2), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
>
> This is not happening in iOS 12.4.  In iOS 13 is resulting not being able to re-start video session when coming back to foreground

Do you have any devices still on iOS 12 to verify this is specific to iOS 13?

**Comment by koke** [comment]
I'm not 100% sure if the background task errors are a red herring, but I went back to the crashes on my device and symbolicated them:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
abort() called

Last Exception Backtrace (0)#0	(null) in __exceptionPreprocess ()
#1	(null) in objc_exception_throw ()
#2	(null) in +[NSException raise:format:arguments:] ()
#3	(null) in -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] ()
#4	(null) in _prepareForCAFlush ()
#5	(null) in _beforeCACommitHandler ()
#6	(null) in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#7	(null) in __CFRunLoopDoObservers ()
#8	(null) in CFRunLoopRunSpecific ()
#9	(null) in -[NSHTMLReader _loadUsingWebKit] ()
#10	(null) in -[NSHTMLReader attributedString] ()
#11	(null) in _NSReadAttributedStringFromURLOrData ()
#12	(null) in -[NSAttributedString+ 99292 (NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] ()
#13	(null) in specialized @nonobjc NSMutableAttributedString.init(data:options:documentAttributes:) (in WordPress) (<compiler-generated>:0)
#14	(null) in WPRichTextFormatter.attributedStringFromHTMLString(_:defaultDocumentAttributes:) (in WordPress) (<compiler-generated>:0)
#15	(null) in specialized static NSAttributedString.attributedStringFromHTMLString(_:defaultAttributes:) (in WordPress) (NSAttributedString+WPRichText.swift:25)
#16	(null) in specialized static WPRichContentView.formattedAttributedStringForString(_:) (in WordPress) (WPRichContentView.swift:83)
#17	(null) in ReaderDetailViewController.configureRichText() (in WordPress) (ReaderDetailViewController.swift:769)
#18	(null) in ReaderDetailViewController.traitCollectionDidChange(_:) (in WordPress) (ReaderDetailViewController.swift:309)
#19	(null) in @objc ReaderDetailViewController.traitCollectionDidChange(_:) (in WordPress) (<compiler-generated>:0)
#20	(null) in -[UIViewController _traitCollectionDidChange:] ()
#21	(null) in -[UIViewController _updateTraitsIfNecessary] ()
#22	(null) in -[UIView+ 15566472 (CALayerDelegate) layoutSublayersOfLayer:] ()
#23	(null) in -[NSObject performSelector:withObject:] ()
#24	(null) in -[CALayer layoutSublayers] ()
#25	(null) in CA::Layer::layout_if_needed+ 1397756 (CA::Transaction*) ()
#26	(null) in -[UIView+ 15483932 (Hierarchy) layoutBelowIfNeeded] ()
#27	(null) in -[UINavigationController _layoutViewController:] ()
#28	(null) in -[UINavigationController _layoutTopViewControllerLookForNested:] ()
#29	(null) in -[UINavigationController _startDeferredTransitionIfNeeded:] ()
#30	(null) in -[UINavigationController __viewWillLayoutSubviews] ()
#31	(null) in -[UILayoutContainerView layoutSubviews] ()
#32	(null) in -[UIView+ 15567548 (CALayerDelegate) layoutSublayersOfLayer:] ()
#33	(null) in -[NSObject performSelector:withObject:] ()
#34	(null) in -[CALayer layoutSublayers] ()
#35	(null) in CA::Layer::layout_if_needed+ 1397756 (CA::Transaction*) ()
#36	(null) in CA::Layer::layout_and_display_if_needed+ 1476964 (CA::Transaction*) ()
#37	(null) in CA::Context::commit_transaction+ 711708 (CA::Transaction*, double) ()
#38	(null) in CA::Transaction::commit+ 887768 () ()
#39	(null) in __83-[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:]_block_invoke_4 ()
#40	(null) in -[UIApplication _performWithUICACommitStateSnapshotting:] ()
#41	(null) in __83-[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:]_block_invoke_2 ()
#42	(null) in +[UIView+ 15511392 (Animation) performWithoutAnimation:] ()
#43	(null) in __83-[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:]_block_invoke ()
#44	(null) in -[UIScene _applyOverrideSettings:forActions:] ()
#45	(null) in -[UIWindowScene _applySnapshotSettings:forActions:] ()
#46	(null) in -[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:] ()
#47	(null) in __65-[UIApplication _performSnapshotsWithAction:forScene:completion:]_block_invoke_3 ()
#48	(null) in -[FBSSceneSnapshotAction _executeNextRequest] ()
#49	(null) in -[FBSSceneSnapshotAction _executeNextRequest] ()
#50	(null) in -[FBSSceneSnapshotAction executeRequestsWithHandler:completionHandler:expirationHandler:] ()
#51	(null) in __65-[UIApplication _performSnapshotsWithAction:forScene:completion:]_block_invoke_2 ()
#52	(null) in -[UIApplication _beginSnapshotSessionForScene:withSnapshotBlock:] ()
#53	(null) in __65-[UIApplication _performSnapshotsWithAction:forScene:completion:]_block_invoke ()
#54	(null) in -[UIScene _enableOverrideSettingsForActions:] ()
#55	(null) in -[UIScene _performSystemSnapshotWithActions:] ()
#56	(null) in -[UIApplication _performSnapshotsWithAction:forScene:completion:] ()
#57	(null) in __98-[_UISceneSnapshotBSActionsHandler _respondToActions:forFBSScene:inUIScene:fromTransitionContext:]_block_invoke_3 ()
#58	(null) in __98-[_UISceneSnapshotBSActionsHandler _respondToActions:forFBSScene:inUIScene:fromTransitionContext:]_block_invoke.30 ()
#59	(null) in -[UIApplication prepareSnapshotsWithAction:forScene:completion:] ()
#60	(null) in __98-[_UISceneSnapshotBSActionsHandler _respondToActions:forFBSScene:inUIScene:fromTransitionContext:]_block_invoke_2 ()
#61	(null) in -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] ()
#62	(null) in -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] ()
#63	(null) in -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] ()
#64	(null) in -[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:] ()
#65	(null) in __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke_2 ()
#66	(null) in -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] ()
#67	(null) in __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke ()
#68	(null) in _dispatch_client_callout ()
#69	(null) in _dispatch_block_invoke_direct ()
#70	(null) in __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ ()
#71	(null) in -[FBSSerialQueue _queue_performNextIfPossible] ()
#72	(null) in -[FBSSerialQueue _performNextFromRunLoopSource] ()
#73	(null) in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#74	(null) in __CFRunLoopDoSource0 ()
#75	(null) in __CFRunLoopDoSources0 ()
#76	(null) in __CFRunLoopRun ()
#77	(null) in CFRunLoopRunSpecific ()
#78	(null) in GSEventRunModal ()
#79	(null) in UIApplicationMain ()
#80	(null) in 0x100604000 ()
#81	(null) in start ()
```

That seems somewhat connected to other errors and why this might only happen with reader posts.

What I understand so far is:

1. When the app goes to the background, iOS tries to take a snapshot (screenshot) of it so it has something to show in the app switcher
2. I remember reading that on iOS 13, the system will make capture a snapshot both in light and dark mode, so you can see the right thing if you change mode while the app is closed. This triggers the `ReaderDetailViewController.traitCollectionDidChange`
3. Because the color scheme has changed, the reader calls `configureRichText` again to regenerate the content.
4. Our rich text view ends up using the `NSAttributedString` initializer that takes HTML. This is implemented using WebKit (as seen in `#9	(null) in -[NSHTMLReader _loadUsingWebKit]`)
5. 🤷‍♂❓ What happens next is a mystery, but we have `NSHTMLReader` running the run loop, presumably waiting for a background WebKit thread to finish parsing the HTML. We also see some WebKit loading errors in the console, although I'm not entirely sure if those are the normal behavior.   

I'm still confused about the fact that I can't reproduce this from Xcode when setting a breakpoint on all exceptions.

**Comment by koke** [comment]
> I'm still confused about the fact that I can't reproduce this from Xcode when setting a breakpoint on all exceptions.

Now it makes sense, this was "fixed" by #12540 two days ago 😅 

Now that fix gets rid of the crash, but it breaks the dual snapshotting, so if you change colors with the app in the background, it will look wrong in the app switcher: [27s](https://cloudup.com/cB7TbrgJgOD)

**Comment by danielebogo** [comment]
Hey @koke nice catch!
I investigated more and I tried a thing I found while I fixed the crash. Create the attributed string in a background thread and assign it in the main one fixes the problem.
I have a rough example here I made it quickly to see if it worked:
```
fileprivate func configureRichText() {
        guard let post = post else {
            return
        }
        textView.isPrivate = post.isPrivate()
        
        DispatchQueue.global(qos: .background).async {
            let attrStr = WPRichContentView.formattedAttributedStringForString(post.contentForDisplay())
            let mAttrStr = NSMutableAttributedString(attributedString: attrStr)

            var paraStyle = NSParagraphStyle.default
            if attrStr.length > 0 {
                if let pstyle = attrStr.attribute(.paragraphStyle, at: 0, effectiveRange: nil) as? NSParagraphStyle {
                    paraStyle = pstyle
                }
            }

            mAttrStr.insert(NSAttributedString(attachment: self.topMarginAttachment), at: 0)
            mAttrStr.addAttributes([.paragraphStyle: paraStyle], range: NSRange(location: 0, length: 1))
            mAttrStr.append(NSAttributedString(attachment: self.bottomMarginAttachment))
            
            DispatchQueue.main.async {
                self.textView.content = post.contentForDisplay()
                self.textView.attributedText = mAttrStr
                self.updateTextViewMargins()
            }
        }
    }
```

**Comment by koke** [comment]
I tried with that change and I can still see the wrong color scheme in the app switcher. I think that might stop the crash because it won't block the main thread, but that also means that the method will return before the view is updated and the snapshot will have the wrong thing.

So far I can think of two solutions:

- Move the attributed string generation to a different solution 🙈 
- Cache the attributed string for both variants on `post.didSet` instead of re-generating it when the traits change

**Comment by danielebogo** [comment]
> Cache the attributed string for both variants on post.didSet instead of re-generating it when the traits change

I like this tbh!!!

**Comment by frosty** [comment]
@koke I don't see the complete wrong color scheme in your video? One thing to note here is that we haven't fully implemented 'dynamic' color scheme changing throughout the app yet – some areas of the app don't respond well if they're already on screen when the colors change. For instant, the gradient views and some of the background views shown in your video. I'm not certain this is a bug introduced by the other PR?

**Comment by koke** [comment]
I noticed the background views also don’t change properly while on the foreground, but what I see is the text color not changing (e.g. white text over white background making it invisible). You can spot that at 0:18 while the app switcher is visible. It immediately fixes itself once the app becomes active

**Comment by danielebogo** [comment]
There are 2 different issues:
The one about the background is already in our todo list (#12320) and it happens even if the app is in foreground. This is part of Dark Mode V2.

The second I think is related to the fix I wrote to avoid the crash and it’s about reloading the text. I was wondering if caching the attributes for both styles can be an easy fix for this.
