### ISSUE TITLE
Inconsistent Display of Weeks in Posting Activity

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/WordPress-iOS#17704]
### Expected behavior
When viewing the full Posting Activity screen from Insights, all months should have consistency with the beginning and ending days for weeks.

### Actual behavior
Over the past twelve months, all go Monday through Sunday top to bottom. Except August, which is displays Sunday through Saturday.

### Steps to reproduce the behavior
Navigate to Stats > Insights, then tap on "View more" on the Posting Activity card.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 13 Pro, iOS 15.2, WPiOS 18.9

**Comment by mdrockwell** [comment]
Here's a screenshot for reference:
![IMG_49F4839185B4-1](https://user-images.githubusercontent.com/42454301/148647445-b07639ff-0401-4e8d-ade8-d9f99ab77ce6.jpeg)

I published each week Monday through Friday last year — aside from that odd weekend in May. August is the only odd month.

**Comment by staskus** [comment]
Note: Still reproducible but for a different month. May be related to months being in different years

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
