### ISSUE TITLE
Share Extension: Image shared from Google Photos app includes link to local file

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5690]
### Expected behavior

I expect images to be shared with either no link or a link to the file on a sharing service.
### Actual behavior

When I share a photo from the Google Photos app, it includes a link to the local image file on my device. (I expect either no link or a link to the file uploaded on Google Photos.)

![Sharing from Google Photos to WordPress](https://cldup.com/UYJZ3Mj1ex.thumb.png)
### Steps to reproduce the behavior
1. Open the Google Photos app
2. Select a photo and tap the sharing icon
3. Select WordPress as the sharing target
4. Note that the sharing dialog includes a link to a local file (beginning `file:///`)

**Comment by jleandroperez** [comment]
Fixed via #5742

**Comment by rachelmcr** [comment]
@jleandroperez This issue is back, seen with both a GIF and a JPG while sharing from Google Photos.

I tested it on iPhone 6, iOS 10.3.1, WPiOS 7.4.0.20170414.

**Comment by jleandroperez** [comment]
@koke mind taking a look at this one?. Sounds like a regression, possibly related to the new helpers?

**Comment by jleandroperez** [comment]
Update: addressed via #7067!
