### ISSUE TITLE
Unread badge count doesn't match in-app unread

### ISSUE THREAD

**Issue by dougaitken** [wordpress-mobile/WordPress-iOS#5864]
### Expected behaviour
Push notification received for activity on wpcom. Badge unread should match what has come through.

### Actual behaviour
Push notification received and badge unread count doesn't match unread.

### Steps to reproduce the behaviour
Unsure, I've experienced this when receiving notifications on high activity posts such as 10th like on A8c site. 

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 5S, iOS 9.3.2, app ver 6.3.1

**Comment by carinapilar** [comment]
I noticed the same problem recently. I'm using an iPhone 6, iOS 9.3.4 and app 6.3.1.

For me it's happening all the time on every post. For example, yesterday I had 2 new notifications, I read and the badge disappeared. Then today, when I logged in on my WordPress.com account on **my computer** the badge on my phone appeared again, with the same notifications from yesterday. It was working perfectly about 2 weeks ago.

**Comment by mzorz** [comment]
This should have been fixed server-side by @daniloercoli today - closing for now 👍

**Comment by carinapilar** [comment]
I'm still having this problem, it was never fixed on my phone at least. It's also not working properly with unread notifications, I read the notifications, then if I get a new one, the previous ones are changed to unread and the badge shows the wrong number.

Had an user complaining about this too, [here](https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3003712).

**Comment by jessefriedman** [comment]
I am having these problems now too.  app notifications are cumulatively coming back. I started with 2 p2 notifications. i cleared them.  then it came back with 3 new ones + the original two so it showed 5. now i'm up to 15. Basically it doesn't seem like the notifications are truly being marked as read.
