### ISSUE TITLE
Post List: Scrolling suddenly halts when syncing ends

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5909]
To reproduce on an iPad. 
- Navigate to the post list for a blog.  
- If there are no posts loaded yet, let the first batch of posts load.  Then tap the back button. Then return to the post list. 
- While the post list is performing its initial sync, quickly swipe to scroll the list. 
- Notice that the list abruptly halts its scrolling when the sync ends. 

You can also trigger this behavior by scrolling to the very end of the list (no more posts to load), re-triggering the load more behavior (a bug in itself maybe?) and scrolling up.

**Comment by hoverduck** [comment]
@aerych - Was this issue iPad-specific?  Has it been resolved by the split-view refresh?  I can't seem to reproduce it.

**Comment by aerych** [comment]
Hiya @hoverduck 
I can still reproduce it. A detail I forgot to include in the description is that the post list won't perform a background sync within five minutes of the last one. 
You can change the refresh interval by editing `AbstractPostListViewController.swift` and changing the value of `postsControllerRefreshInterval` to something like `3` instead of `300`.  The `TimeInterval` is a value representing seconds, so this would mean the list would perform its background sync as long as it had been at least 3 seconds since the last time it tried to sync. 
Another helpful trick is to use Apple's Network Link Conditioner to throttle your bandwidth down to Edge speeds for more time to scroll before the request completes.

**Comment by kean** [comment]
Closing as obsolete.
