### ISSUE TITLE
Customizer: Keyboard dismisses after typing each character in some text fields

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6371]
### Expected behavior

I should be able to type without interruptions in text fields in the customizer, the same as when using the customizer in a web browser.

### Actual behavior

When typing in some text fields in the customizer, the keyboard is dismissed after typing each character. This seems to happen in text fields that update the customizer's live preview, such as:

- Text in widgets (e.g. any widget title field)
- Featured content tag field (for themes with a Featured Content section)
- Portfolio "archive title" and "archive content" fields (for themes with a Portfolio section)

This is only an issue in the iOS app, not web browsers or the Android app.

### Steps to reproduce the behavior

1. Go to Themes > Customize in the app to open the customizer
2. Open the Widgets section
3. Open a widget area and add a widget
4. Start typing in the widget title field

Result: The keyboard dismisses after typing every character (or if I type quickly, after every 2-3 characters)

**Comment by koke** [comment]
I can't reproduce this in 6.8.0.20170112, maybe it was fixed on WordPress.com, or it depends on the theme?

**Comment by rachelmcr** [comment]
I re-tested and can still reproduce this in 6.8.0.20170112. I tested on a site using the Ixion theme, in case that's a factor.

**Comment by koke** [comment]
Confirmed, I can reproduce with Ixion (and many others, just not Twenty Twelve)

**Comment by rachelmcr** [comment]
A beta tester reported the same keyboard issue in the customizer:

> My keyboard, both Gboard & stock on iOS were jumping away.

**Comment by elibud** [comment]
We are putting this on hold. The solution seems to be updating to the new WKWebView, but we cannot do that yet since it has a bug and it doesn't send POST body data which we use for Authentication. The bug on WKWebView has been fixed and should be released soon, at that stage we can re visit this issue, and maybe update to WKWebView at least for the users that have the right iOS version.

**Comment by catehstn** [comment]
How feasible is it to use WKWebView iff the user is on iOS 11 or above? Because this bug makes the customizer very hard to use - would be good to fix it for some, even if not everyone.

**Comment by elibud** [comment]
@catehstn it shouldn't be too hard. It won't look pretty though (code-wise), because the delegate methods for UIWebView and WKWebView are not the same, so the controllers that alternatively use one or the other would have to implement both protocols. 
We may come up with a more clever way to encapsulate that difference with a third adapter protocol or sth like that?
I agree that we should still do it once iOS 11 is available, it should provide improvements not only for the customizer, but for previews too.

**Comment by catehstn** [comment]
Yeah, or a custom view that just contains whichever depending on OS version, that then passes events on via a protocol that hides the difference between them. Basically just hide the horrible in one class with a sensible interface around it.

**Comment by koke** [comment]
There's also one thing we could try before iOS11, it sounds hacky but it might just work. Instead of using a POST request to wp-login, we could load a fake invisible HTML form with the right base URL, and submit that using JavaScript. That wouldn't work with Oauth2 tokens right away but it's easier to find alternatives for wp.com login.

**Comment by rachelmcr** [comment]
Just a note that this came up again in user feedback (Ref: AppbotX 28827) and is a blocker for working with some widgets in the app:

> I was trying to add the Follow Blog via Email widget and customise the text fields, and I was very annoyed because the keyboard can never stay up for more than 0.25 seconds for me to type anything. In the end I gave up and added the widget via my computer because it was way faster and easier.

**Comment by rachelmcr** [comment]
Noting that this came up again in a chat with an iPad user (internal ref: 424847-hc and 3256088-t) who was trying to set up the audio player widget in the customizer.

**Comment by rachelmcr** [comment]
This was reported again through in-app feedback:

> So many issues. Most importantly editing the widgets is a pain. Keyboard keeps vanishing.

Internal ref: AppbotX 29711

**Comment by elibud** [comment]
Assigning to @koke since it's fixed on his PR https://github.com/wordpress-mobile/WordPress-iOS/pull/7921
