### ISSUE TITLE
Notification images persist on cell when presenting a new notification with image.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9778]
### Expected behavior
I shouldn't see the image of a previous notification on a new notification.

### Actual behavior

When presenting a new notification with image, an image of a previously presented notification will appear for a brief moment, while the new image is loading.

### Steps to reproduce the behavior

On an iPhone: 
- Open a notification with an image.
- Navigate to the previous notification using the top-right arrows.
- When a notification with image is opened (and if the image wasn't previously loaded), it will show the previous image for a short time.

An example can be found [on this video](https://cloudup.com/c9Mql_bNk0p).

**Comment by frosty** [comment]
May also be fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/10761

(Thanks for the heads-up @stevebaranski!)

**Comment by etoledom** [comment]
I was able to reproduce this issue building from the #10761 branch. So this is still not solved 😞

**Comment by stevebaranski** [comment]
Sorry to hear that @etoledom. I appreciate you investigating it.

@frosty I can make some time this week to investigate this particular issue. Sound good?

**Comment by frosty** [comment]
Sure, if you want to pick this one up then go for it! :)
